// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  공유 데이터 - 가이드 & 투어 목록
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export const ALL_GUIDES = [
  // ─── 태국 ───
  {
    id: 'g-th-01', country: 'TH', flag: '🇹🇭', countryName: '태국', city: '방콕',
    name: '김현우 (방콕 10년 교민)',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=160&h=160&fit=crop&crop=face',
    tagline: '방콕 현지인이 가는 진짜 맛집만 알려드립니다',
    rating: 4.97, reviews: 312, guides_done: 480, lang: ['한국어','태국어','영어'],
    verified: true, super: true,
    tags: ['#가성비맛집', '#나이트투어', '#교통안내', '#응급대처'],
    badge: '🏆 슈퍼가이드',
    themes: ['일반', '남성전용'],
    intro: '방콕 거주 10년 교민입니다. 현지 로컬 맛집부터 야시장, 마사지샵까지 바가지 없는 진짜 방콕을 안내합니다. 24시간 카톡 지원.',
    support_price: 10000,
    tours: ['t-th-01', 't-th-02', 't-th-03'],
  },
  {
    id: 'g-th-02', country: 'TH', flag: '🇹🇭', countryName: '태국', city: '파타야',
    name: '박지훈 (파타야 전문)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=160&h=160&fit=crop&crop=face',
    tagline: '파타야 A to Z, 숙소부터 나이트까지 완벽 케어',
    rating: 4.92, reviews: 198, guides_done: 290, lang: ['한국어','태국어'],
    verified: true, super: false,
    tags: ['#파타야비치', '#워킹스트리트', '#가성비숙소', '#마사지'],
    badge: '⭐ 인기가이드',
    themes: ['일반', '남성전용'],
    intro: '파타야 5년 거주. 깨끗하고 저렴한 숙소, 바가지 없는 투어, 현지 음식점 완벽 안내. 픽업 서비스 가능.',
    support_price: 10000,
    tours: ['t-th-04', 't-th-05'],
  },
  // ─── 베트남 ───
  {
    id: 'g-vn-01', country: 'VN', flag: '🇻🇳', countryName: '베트남', city: '다낭',
    name: '이수진 (다낭 교민 8년)',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=160&h=160&fit=crop&crop=face',
    tagline: '미케비치 맛집 500곳 섭렵한 다낭 전문가',
    rating: 4.98, reviews: 421, guides_done: 560, lang: ['한국어','베트남어','영어'],
    verified: true, super: true,
    tags: ['#미케비치', '#현지맛집', '#바나힐', '#여성여행'],
    badge: '🏆 슈퍼가이드',
    themes: ['일반', '가족', '커플'],
    intro: '다낭 8년 거주 교민. 아이와 함께하는 가족여행부터 커플 여행까지 맞춤 코스 구성. 호이안 당일치기 필수코스 보유.',
    support_price: 10000,
    tours: ['t-vn-01', 't-vn-02'],
  },
  {
    id: 'g-vn-02', country: 'VN', flag: '🇻🇳', countryName: '베트남', city: '호치민',
    name: '최민석 (호치민 7년)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=160&h=160&fit=crop&crop=face',
    tagline: '사이공의 모든 것 - 맛집, 클럽, 쇼핑 원스탑',
    rating: 4.89, reviews: 256, guides_done: 340, lang: ['한국어','베트남어'],
    verified: true, super: false,
    tags: ['#분짜맛집', '#벤탄시장', '#나이트라이프', '#쇼핑'],
    badge: '⭐ 인기가이드',
    themes: ['일반', '남성전용', '쇼핑'],
    intro: '호치민 7년 교민. 벤탄시장 흥정부터 루프탑바, 클럽 스트리트까지 생생한 현지 정보 제공.',
    support_price: 10000,
    tours: ['t-vn-03', 't-vn-04'],
  },
  // ─── 일본 ───
  {
    id: 'g-jp-01', country: 'JP', flag: '🇯🇵', countryName: '일본', city: '오사카',
    name: '정다은 (오사카 유학 5년)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=160&h=160&fit=crop&crop=face',
    tagline: '오사카 도톤보리 맛집 지도 직접 제작한 푸드가이드',
    rating: 4.95, reviews: 388, guides_done: 510, lang: ['한국어','일본어'],
    verified: true, super: true,
    tags: ['#도톤보리', '#맛집투어', '#아리마온천', '#라멘맛집'],
    badge: '🏆 슈퍼가이드',
    themes: ['일반', '맛집', '커플'],
    intro: '오사카 유학 5년. 줄 안 서는 맛집 루트, 유니버설 꿀팁, 교토·나라 당일치기 완벽 가이드.',
    support_price: 15000,
    tours: ['t-jp-01', 't-jp-02'],
  },
  {
    id: 'g-jp-02', country: 'JP', flag: '🇯🇵', countryName: '일본', city: '도쿄',
    name: '강민준 (도쿄 직장인 6년)',
    avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=160&h=160&fit=crop&crop=face',
    tagline: '도쿄 현지 직장인이 퇴근 후 가는 진짜 이자카야',
    rating: 4.91, reviews: 201, guides_done: 278, lang: ['한국어','일본어','영어'],
    verified: true, super: false,
    tags: ['#이자카야', '#시부야', '#전철꿀팁', '#남성전용'],
    badge: '⭐ 인기가이드',
    themes: ['일반', '남성전용', '나이트'],
    intro: '도쿄 6년 직장인. 관광객이 모르는 골목 이자카야, 롯폰기 나이트라이프, 저렴한 교통패스 완벽 안내.',
    support_price: 15000,
    tours: ['t-jp-03'],
  },
  // ─── 라오스 ───
  {
    id: 'g-la-01', country: 'LA', flag: '🇱🇦', countryName: '라오스', city: '비엔티안',
    name: '송재원 (라오스 NGO 4년)',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=160&h=160&fit=crop&crop=face',
    tagline: '라오스 로컬 버스부터 숨겨진 폭포까지 알려드립니다',
    rating: 4.88, reviews: 145, guides_done: 180, lang: ['한국어','라오어','영어'],
    verified: true, super: false,
    tags: ['#슬로여행', '#방비엥투빙', '#루앙프라방', '#저예산'],
    badge: '✅ 인증가이드',
    themes: ['일반', '배낭여행', '힐링'],
    intro: 'NGO 활동 4년, 라오스 전역 정통한 가이드. 루앙프라방 알무스기빙, 방비엥 투빙, 타켁 동굴 전문.',
    support_price: 8000,
    tours: ['t-la-01'],
  },
]

export const ALL_TOURS = [
  // ─── 태국 방콕 ───
  {
    id: 't-th-01', guideId: 'g-th-01', country: 'TH', flag: '🇹🇭', city: '방콕',
    title: '방콕 현지인 맛집 + 야시장 투어',
    theme: '일반', duration: '1일', groupSize: '1~8명',
    price: 45000, depositRate: 30,
    rating: 4.97, reviews: 189,
    img: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed?w=600&h=400&fit=crop',
    tags: ['#로컬맛집', '#야시장', '#저녁코스'],
    includes: ['로컬 식당 3곳 안내', '야시장 흥정 도움', '교통 동행', '24시 카톡 지원'],
    excludes: ['개인 식비', '교통비'],
    schedule: [
      { time: '18:00', desc: '오어터(Or Tor Kor) 재래시장 - 현지 과일·식재료' },
      { time: '19:30', desc: '로컬 쌀국수 맛집 (관광객 없는 골목)' },
      { time: '21:00', desc: '차이나타운 야오와랏 야시장 탐방' },
      { time: '22:30', desc: '현지 빙수·디저트 마무리' },
    ],
    mapQuery: 'Or+Tor+Kor+Market+Bangkok',
    isHot: true,
  },
  {
    id: 't-th-02', guideId: 'g-th-01', country: 'TH', flag: '🇹🇭', city: '방콕',
    title: '방콕 왕궁·사원 + 수상시장 풀코스',
    theme: '일반', duration: '1일', groupSize: '1~6명',
    price: 60000, depositRate: 30,
    rating: 4.95, reviews: 143,
    img: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop',
    tags: ['#왕궁', '#수상시장', '#사원투어'],
    includes: ['가이드 동행', '보트 예약 대행', '입장료 안내', '점심 맛집 추천'],
    excludes: ['입장료', '식비', '교통비'],
    schedule: [
      { time: '07:30', desc: '담넌사두억 수상시장 출발' },
      { time: '10:00', desc: '왓포 사원 (와불)' },
      { time: '12:00', desc: '로컬 식당 점심' },
      { time: '14:00', desc: '왕궁 & 에메랄드 사원' },
      { time: '17:00', desc: '짜오프라야강 선셋 유람선' },
    ],
    mapQuery: 'Grand+Palace+Bangkok',
    isHot: false,
  },
  {
    id: 't-th-03', guideId: 'g-th-01', country: 'TH', flag: '🇹🇭', city: '방콕',
    title: '방콕 남성 전용 나이트 투어 🔞',
    theme: '남성전용', duration: '1일 저녁', groupSize: '1~4명',
    price: 80000, depositRate: 50,
    rating: 4.98, reviews: 98,
    img: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?w=600&h=400&fit=crop',
    tags: ['#나나플라자', '#카우산로드', '#마사지', '#루프탑바'],
    includes: ['가이드 동행 4시간', '업소 가격표 사전 공유', '바가지 방지 동행', '귀가 안전 안내'],
    excludes: ['개인 소비', '입장료'],
    schedule: [
      { time: '20:00', desc: '수쿰빗 로컬 이자카야·맥주' },
      { time: '21:30', desc: '아소크 나나 구역 탐방 (가이드 동행)' },
      { time: '23:00', desc: '전통 마사지 추천샵 (가격표 오픈)' },
      { time: '01:00', desc: '카우산로드 마무리 또는 귀가' },
    ],
    mapQuery: 'Nana+Plaza+Bangkok',
    isHot: true,
    matureTag: true,
  },
  {
    id: 't-th-04', guideId: 'g-th-02', country: 'TH', flag: '🇹🇭', city: '파타야',
    title: '파타야 해변 + 코란섬 스노클링',
    theme: '일반', duration: '1일', groupSize: '1~10명',
    price: 55000, depositRate: 30,
    rating: 4.92, reviews: 112,
    img: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&h=400&fit=crop',
    tags: ['#코란섬', '#스노클링', '#파타야비치', '#해산물'],
    includes: ['스피드보트 예약', '스노클링 장비', '점심 해산물', '가이드 동행'],
    excludes: ['개인 음료', '추가 액티비티'],
    schedule: [
      { time: '08:00', desc: '파타야 선착장 출발 → 코란섬' },
      { time: '09:30', desc: '스노클링 & 해수욕' },
      { time: '12:00', desc: '현지 해산물 레스토랑 점심' },
      { time: '15:00', desc: '파타야 비치 자유시간' },
      { time: '18:00', desc: '해변 선셋 & 로컬 저녁식당' },
    ],
    mapQuery: 'Koh+Larn+Pattaya',
    isHot: false,
  },
  {
    id: 't-th-05', guideId: 'g-th-02', country: 'TH', flag: '🇹🇭', city: '파타야',
    title: '파타야 남성 전용 워킹스트리트 투어 🔞',
    theme: '남성전용', duration: '1일 저녁', groupSize: '1~6명',
    price: 70000, depositRate: 50,
    rating: 4.91, reviews: 87,
    img: 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?w=600&h=400&fit=crop',
    tags: ['#워킹스트리트', '#마사지', '#나이트바', '#바가지없음'],
    includes: ['가이드 동행 4시간', '업소 가격표 사전 공유', '흥정 도움', '귀가 안전'],
    excludes: ['개인 소비'],
    schedule: [
      { time: '19:00', desc: '로컬 씨푸드 저녁' },
      { time: '20:30', desc: '워킹스트리트 투어 (가이드 동행)' },
      { time: '22:00', desc: '추천 마사지샵 (가격표 사전 공유)' },
      { time: '00:00', desc: '귀가 또는 자유시간' },
    ],
    mapQuery: 'Walking+Street+Pattaya',
    isHot: false,
    matureTag: true,
  },
  // ─── 베트남 다낭 ───
  {
    id: 't-vn-01', guideId: 'g-vn-01', country: 'VN', flag: '🇻🇳', city: '다낭',
    title: '다낭 미케비치 + 호이안 구시가지 풀데이',
    theme: '일반', duration: '1일', groupSize: '1~8명',
    price: 40000, depositRate: 30,
    rating: 4.98, reviews: 234,
    img: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&h=400&fit=crop',
    tags: ['#미케비치', '#호이안', '#랜턴시장', '#쌀국수'],
    includes: ['차량 픽업', '가이드 동행 전일', '로컬 맛집 3곳', '호이안 야경 안내'],
    excludes: ['식비', '입장료', '란턴 구매'],
    schedule: [
      { time: '09:00', desc: '미케비치 해변 산책 & 해산물 아침' },
      { time: '11:00', desc: '바나힐 케이블카 (선택)' },
      { time: '14:00', desc: '호이안 구시가지 이동' },
      { time: '15:00', desc: '로컬 까우라우·화이트로즈 맛집' },
      { time: '19:00', desc: '호이안 야시장 & 란턴 띄우기' },
    ],
    mapQuery: 'Hoi+An+Ancient+Town+Vietnam',
    isHot: true,
  },
  {
    id: 't-vn-02', guideId: 'g-vn-01', country: 'VN', flag: '🇻🇳', city: '다낭',
    title: '다낭 현지 맛집 투어 (점심+저녁)',
    theme: '맛집', duration: '반일', groupSize: '1~6명',
    price: 25000, depositRate: 20,
    rating: 4.97, reviews: 187,
    img: 'https://images.unsplash.com/photo-1600334129128-685c5582fd35?w=600&h=400&fit=crop',
    tags: ['#쌀국수', '#미꽝', '#반쎄오', '#현지맛집'],
    includes: ['가이드 동행', '맛집 5곳 순회', '식당 흥정 도움', '메뉴 번역'],
    excludes: ['식비'],
    schedule: [
      { time: '11:30', desc: '미꽝(Mi Quang) 원조 로컬식당' },
      { time: '13:00', desc: '반미(Banh Mi) 맛집' },
      { time: '14:30', desc: '다낭 재래시장 식재료 구경' },
      { time: '18:00', desc: '반쎄오(Banh Xeo) 저녁' },
      { time: '19:30', desc: '에그커피 & 다낭 야경' },
    ],
    mapQuery: 'Da+Nang+Local+Food+Market',
    isHot: false,
  },
  {
    id: 't-vn-03', guideId: 'g-vn-02', country: 'VN', flag: '🇻🇳', city: '호치민',
    title: '호치민 역사지구 + 로컬 쌀국수 투어',
    theme: '일반', duration: '1일', groupSize: '1~8명',
    price: 38000, depositRate: 30,
    rating: 4.89, reviews: 156,
    img: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&h=400&fit=crop',
    tags: ['#통일궁', '#전쟁박물관', '#분짜', '#벤탄시장'],
    includes: ['가이드 동행 전일', '교통 안내', '맛집 2곳', '시장 흥정 도움'],
    excludes: ['식비', '입장료', '교통비'],
    schedule: [
      { time: '08:30', desc: '분짜(Bun Cha) 아침 - 현지 로컬 식당' },
      { time: '10:00', desc: '전쟁박물관 & 통일궁' },
      { time: '13:00', desc: '벤탄시장 흥정 & 쇼핑' },
      { time: '15:00', desc: '사이공 루프탑바 커피' },
      { time: '19:00', desc: '분보(Bun Bo Hue) 저녁 로컬 식당' },
    ],
    mapQuery: 'Ben+Thanh+Market+Ho+Chi+Minh',
    isHot: false,
  },
  {
    id: 't-vn-04', guideId: 'g-vn-02', country: 'VN', flag: '🇻🇳', city: '호치민',
    title: '호치민 남성 전용 부이비엔 나이트 투어 🔞',
    theme: '남성전용', duration: '1일 저녁', groupSize: '1~4명',
    price: 65000, depositRate: 50,
    rating: 4.88, reviews: 73,
    img: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&h=400&fit=crop',
    tags: ['#부이비엔', '#마사지', '#루프탑바', '#나이트라이프'],
    includes: ['가이드 동행 4시간', '가격표 사전 공유', '바가지 방지', '안전 귀가'],
    excludes: ['개인 소비'],
    schedule: [
      { time: '19:30', desc: '로컬 맥주&안주 저녁' },
      { time: '21:00', desc: '부이비엔 거리 투어 (가이드 동행)' },
      { time: '22:30', desc: '추천 마사지샵 (가격표 오픈)' },
      { time: '00:00', desc: '귀가 또는 자유시간' },
    ],
    mapQuery: 'Bui+Vien+Street+Ho+Chi+Minh',
    isHot: false,
    matureTag: true,
  },
  // ─── 일본 오사카 ───
  {
    id: 't-jp-01', guideId: 'g-jp-01', country: 'JP', flag: '🇯🇵', city: '오사카',
    title: '오사카 도톤보리 맛집 + 낮술 투어',
    theme: '맛집', duration: '1일', groupSize: '1~6명',
    price: 55000, depositRate: 30,
    rating: 4.95, reviews: 267,
    img: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&h=400&fit=crop',
    tags: ['#도톤보리', '#타코야키', '#오코노미야키', '#이자카야'],
    includes: ['가이드 동행 전일', '맛집 5곳 예약 대행', '메뉴 번역', 'IC카드 사용법'],
    excludes: ['식비', '교통비'],
    schedule: [
      { time: '11:00', desc: '이치란 라멘 (개인부스 예약)' },
      { time: '13:00', desc: '도톤보리 타코야키 & 오코노미야키' },
      { time: '15:00', desc: '구로몬 시장 - 해산물 시식' },
      { time: '17:00', desc: '신세카이 낮술 이자카야' },
      { time: '19:30', desc: '난바 야키토리 골목' },
    ],
    mapQuery: 'Dotonbori+Osaka',
    isHot: true,
  },
  {
    id: 't-jp-02', guideId: 'g-jp-01', country: 'JP', flag: '🇯🇵', city: '오사카',
    title: '교토 당일치기 - 기온·아라시야마 완벽코스',
    theme: '일반', duration: '1일', groupSize: '1~6명',
    price: 65000, depositRate: 30,
    rating: 4.96, reviews: 189,
    img: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&h=400&fit=crop',
    tags: ['#교토', '#기온', '#아라시야마', '#금각사'],
    includes: ['기차 예약 대행', '가이드 동행', '점심 로컬식당', '입장 줄서기 방지 팁'],
    excludes: ['교통비', '입장료', '식비'],
    schedule: [
      { time: '08:00', desc: '오사카 출발 → 교토 신칸센' },
      { time: '09:30', desc: '아라시야마 대나무숲 (이른 아침 한산)' },
      { time: '11:30', desc: '텐류지 정원 & 도게츠교 다리' },
      { time: '13:00', desc: '교토 로컬 두부 정식 점심' },
      { time: '15:00', desc: '기온 거리 & 야사카 신사' },
      { time: '17:30', desc: '금각사 황금빛 일몰' },
    ],
    mapQuery: 'Arashiyama+Kyoto',
    isHot: false,
  },
  {
    id: 't-jp-03', guideId: 'g-jp-02', country: 'JP', flag: '🇯🇵', city: '도쿄',
    title: '도쿄 현지인 이자카야 + 시부야 나이트 투어',
    theme: '남성전용', duration: '1일 저녁', groupSize: '1~4명',
    price: 70000, depositRate: 40,
    rating: 4.91, reviews: 134,
    img: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&h=400&fit=crop',
    tags: ['#이자카야', '#시부야', '#롯폰기', '#현지술집'],
    includes: ['가이드 동행 4시간', '현지 이자카야 예약', '메뉴 번역', '전철 안내'],
    excludes: ['식비', '주류비', '교통비'],
    schedule: [
      { time: '18:30', desc: '시부야 스크램블 교차로 사진' },
      { time: '19:00', desc: '현지인 단골 야키토리 이자카야' },
      { time: '21:00', desc: '시부야 바 골목 크롤' },
      { time: '23:00', desc: '롯폰기 클럽 or 귀가' },
    ],
    mapQuery: 'Shibuya+Tokyo+Night',
    isHot: false,
    matureTag: true,
  },
  // ─── 라오스 ───
  {
    id: 't-la-01', guideId: 'g-la-01', country: 'LA', flag: '🇱🇦', city: '방비엥',
    title: '방비엥 투빙 + 블루라군 + 동굴 탐험',
    theme: '일반', duration: '1일', groupSize: '1~10명',
    price: 30000, depositRate: 30,
    rating: 4.88, reviews: 98,
    img: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop',
    tags: ['#투빙', '#블루라군', '#동굴', '#배낭여행'],
    includes: ['투빙 장비', '블루라군 입장', '동굴 안내', '현지 도시락'],
    excludes: ['교통비'],
    schedule: [
      { time: '08:00', desc: '남쏭강 투빙 (튜브 타기)' },
      { time: '11:00', desc: '블루라군 1 수영' },
      { time: '13:00', desc: '현지 식당 점심' },
      { time: '15:00', desc: '탐창 동굴 탐험' },
      { time: '17:30', desc: '방비엥 선셋 뷰포인트' },
    ],
    mapQuery: 'Blue+Lagoon+Vang+Vieng+Laos',
    isHot: false,
  },
]

// 가이드 ID로 빠른 조회
export const GUIDE_MAP: Record<string, typeof ALL_GUIDES[0]> = {}
ALL_GUIDES.forEach(g => { GUIDE_MAP[g.id] = g })

// 투어 ID로 빠른 조회
export const TOUR_MAP: Record<string, typeof ALL_TOURS[0]> = {}
ALL_TOURS.forEach(t => { TOUR_MAP[t.id] = t })
